name: CI build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala: [2.12.13, 2.13.3]
        jvm: [openjdk@1.11]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v6
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: ${{ matrix.jvm }}
      - name: Clean, Check code formatting, compile, test, generate coverage report
        run: sbt ++${{ matrix.scala }} clean scalafmtCheck test:scalafmtCheck compile coverage chimney/test chimney/coverageReport
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
